language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

matrix:
  allow_failures:
    - php: '7.1'
    - php: 'hhvm'

sudo: false

before_script:
  - composer self-update
  - composer install

cache:
  directories:
    - ./vendor

script: vendor/bin/phpunit -c phpunit.xml